name: check
on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual triggering
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v11
      - uses: DeterminateSystems/flake-checker-action@v7
      - uses: DeterminateSystems/magic-nix-cache-action@v6
      - run: nix flake check
